name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.DOCKER_USERNAME }}/crc-bot:latest
          cache-from: type=registry,ref=ghcr.io/${{ secrets.DOCKER_USERNAME }}/crc-bot:cache
          cache-to: type=registry,ref=ghcr.io/${{ secrets.DOCKER_USERNAME }}/crc-bot:cache,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ghcr.io/${{ secrets.DOCKER_USERNAME }}/crc-bot:latest
            docker stop crc-bot || true
            docker rm crc-bot || true
            docker run -d \
              --name crc-bot \
              --restart unless-stopped \
              --env-file bot/config/crc-bot.env \
              ghcr.io/${{ secrets.DOCKER_USERNAME }}/crc-bot:latest
