name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/crc-bot:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/crc-bot:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ghcr.io/${{ secrets.DOCKER_USERNAME }}/crc-bot:latest
            docker stop crc-bot || true
            docker rm crc-bot || true
            docker run -d --name --restart unless-stopped --env-file bot/config/crc-bot.env ghcr.io/${{ secrets.DOCKER_USERNAME }}/crc-bot:latest
