name: Migrate

on:
  workflow_dispatch:
  push:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.17

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile

      - name: Migrate database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          bun db:push
