name: Migrate

on:
  workflow_dispatch:
  push:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.17

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.BOT_SECRETS }}" >> .env

      - name: DEBUG
        run: |
          cat .env
          ls

      - name: Install dependencies
        run: |
          bun install

      - name: Migrate database
        run: |
          bun db:push
