name: Migrate

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/lib/db/**/*'
      - '.github/workflows/migrate.yml'

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.17

      - name: Install dependencies
        run: |
          bun install

      - name: Migrate database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          bun db:push
